const TEXT = {
  en: {
    title: 'User Preference Study for 3D Scene Editing Results',
    p1: `This questionnaire aims to evaluate the quality of 3D scene editing results.
In each question, you will be shown an original 3D scene, an editing instruction,
and two edited results generated by different systems. To ensure a fair and
unbiased evaluation, all results are anonymized and presented only as Result A
and Result B. No method names or system identities will be disclosed.`,
    p2: `Please choose the result that you think is better based on your visual judgment.
When making your decision, please consider whether the edited result accurately
follows the given instruction, whether the object placement and spatial
relationships are reasonable, whether there are obvious physical issues such as
collisions, floating objects, or penetrations, and whether the overall scene
appears natural and plausible.`,
    p3: `There is no standard answer in this questionnaire. Please answer independently
based on what you observe. This questionnaire is used for academic research only.
All responses will be collected and analyzed anonymously, and no personally
identifiable information will be collected. Thank you for your participation and
support.`,
    consent: `By clicking “Start Questionnaire”, you confirm that you agree to participate in
this user study and allow your anonymous questionnaire responses to be collected
and used for academic research.`,
    start: 'Start Questionnaire',
  },
  zh: {
    title: '3D 场景编辑结果用户偏好调研',
    p1: `本问卷旨在评估 3D 场景编辑结果的质量。在每一道题中，你将看到一个原始 3D 场景、一条编辑指令，以及由不同系统生成的两个编辑结果。为了保证评估公平，所有结果都会匿名展示为 Result A 和 Result B，不会显示任何方法名称或系统身份。`,
    p2: `请根据你的视觉判断选择你认为更好的结果。判断时请考虑：编辑结果是否准确遵循给定指令，物体放置和空间关系是否合理，是否存在明显的物理问题，例如碰撞、悬浮或穿插，以及整体场景是否自然、合理。`,
    p3: `本问卷没有标准答案，请根据你观察到的内容独立作答。本问卷仅用于学术研究，所有回答将以匿名方式收集和分析，不会收集任何可识别个人身份的信息。感谢你的参与和支持。`,
    consent: `点击“开始问卷”即表示你同意参与本次用户研究，并同意你的匿名问卷回答被收集并用于学术研究。`,
    start: '开始问卷',
  }
}

function IntroPage({ lang, setLang, onStart }) {
  const t = TEXT[lang]

  return (
    <main className="page">
      <section className="intro-card">
        <div className="language-switch">
          <button onClick={() => setLang('en')} className={lang === 'en' ? 'active' : ''}>
            English
          </button>
          <button onClick={() => setLang('zh')} className={lang === 'zh' ? 'active' : ''}>
            中文
          </button>
        </div>

        <h1>{t.title}</h1>

        <p>{t.p1}</p>
        <p>{t.p2}</p>
        <p>{t.p3}</p>

        <p className="consent-text">{t.consent}</p>

        <button className="primary-button" onClick={onStart}>
          {t.start}
        </button>
      </section>
    </main>
  )
}

export default IntroPage