function IntroPage({ onStart }) {
  return (
    <main className="page">
      <section className="intro-card">
        <h1>User Preference Study for 3D Scene Editing Results</h1>

        <p>
          This questionnaire aims to evaluate the quality of 3D scene editing results.
          In each question, you will be shown an original 3D scene, an editing instruction,
          and two edited results generated by different systems. To ensure a fair and
          unbiased evaluation, all results are anonymized and presented only as Result A
          and Result B. No method names or system identities will be disclosed.
        </p>

        <p>
          Please choose the result that you think is better based on your visual judgment.
          When making your decision, please consider whether the edited result accurately
          follows the given instruction, whether the object placement and spatial
          relationships are reasonable, whether there are obvious physical issues such as
          collisions, floating objects, or penetrations, and whether the overall scene
          appears natural and plausible. If the two results are similar in quality, or if
          you cannot clearly determine which one is better, you may select “No clear
          preference.”
        </p>

        <p>
          There is no standard answer in this questionnaire. Please answer independently
          based on what you observe. This questionnaire is used for academic research only.
          All responses will be collected and analyzed anonymously, and no personally
          identifiable information will be collected. Thank you for your participation and
          support.
        </p>

        <p className="consent-text">
          By clicking “Start Questionnaire”, you confirm that you agree to participate in
          this user study and allow your anonymous questionnaire responses to be collected
          and used for academic research.
        </p>

        <button className="primary-button" onClick={onStart}>
          Start Questionnaire
        </button>
      </section>
    </main>
  )
}

export default IntroPage